#ifndef WT_CONFIG_H
#define WT_CONFIG_H

#define STATUS_POLLING_MS 300
#define LED_SLEEP_TIME_MS 250
#define WT_TX_PAYLOAD_MAX 255
#define WT_BLE_NOTIFY_APP_PAYLOAD_MAX 255
#define WT_BLE_STATUS_TEXT_MAX 255
#define WT_BLE_CMD_TEXT_MAX 255
#define WT_BLE_CMD_RSP_TEXT_MAX 255
#define WT_BLE_STATUS_PING_MS 5000
#define WT_BLE_ADV_RESTART_DELAY_MS 250
#define WT_BLE_SELF_STOP_DELAY_MS 500
#define WT_WIFI_CRED_TIMEOUT_SEC CONFIG_STA_CONN_TIMEOUT_SEC

#define WT_WIFI_CMD_UDP_PORT 5001
#define WT_WIFI_CMD_RX_TEXT_MAX 255
#define WT_WIFI_CMD_RSP_TEXT_MAX 255
#define WT_WIFI_CMD_THREAD_STACK_SIZE 4096
#define WT_WIFI_CMD_THREAD_PRIORITY 7

#endif /* WT_CONFIG_H */
