#ifndef WT_CONFIG_H
#define WT_CONFIG_H

#define STATUS_POLLING_MS 300
#define LED_SLEEP_TIME_MS 250
#define WT_BLE_NOTIFY_RETRY_COUNT 8
#define WT_BLE_NOTIFY_RETRY_DELAY_MS 20
#define WT_BLE_NOTIFY_INTER_CHUNK_DELAY_MS 12
#define WT_TX_PAYLOAD_MAX 244
#define WT_BLE_NOTIFY_APP_PAYLOAD_MAX 244
#define WT_BLE_STREAM_CHUNK_OVERHEAD 8
#define WT_BLE_STATUS_TEXT_MAX 250
#define WT_BLE_CMD_TEXT_MAX 255
#define WT_BLE_CMD_RSP_TEXT_MAX 250
#define WT_BLE_STATUS_PING_MS 5000
#define WT_BLE_ADV_RESTART_DELAY_MS 250
#define WT_BLE_SELF_STOP_DELAY_MS 500
#define WT_WIFI_CRED_TIMEOUT_SEC CONFIG_STA_CONN_TIMEOUT_SEC

#define WT_WIFI_CMD_UDP_PORT 5001
#define WT_WIFI_CMD_RX_TEXT_MAX 255
#define WT_WIFI_CMD_RSP_TEXT_MAX 250
#define WT_WIFI_CMD_THREAD_STACK_SIZE 4096
#define WT_WIFI_CMD_THREAD_PRIORITY 7
#define WT_WIFI_DISCOVERY_UDP_PORT 5000
#define WT_WIFI_DISCOVERY_INTERVAL_MS 5000
#define WT_WIFI_DISCOVERY_PAYLOAD_MAX 250
#define WT_WIFI_SCAN_MAX_RESULTS 10
#define WT_WIFI_SCAN_TIMEOUT_MS 12000
#define WT_BLE_NAME_MAX 31

#define WT_APP_BOOT_MODE_MAX 8
#define WT_APP_DELAYED_ACTION_MAX 16
#define WT_APP_REBOOT_DELAY_MS 500
#define WT_APP_BRIDGE_TARGET_MAX 47

#endif /* WT_CONFIG_H */
